name: Python CI

on: [push, pull_request]  # Triggers on push/PR to any branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checks out your code
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Run tests
        run: |
          python -m unittest todo_app/test_app.py