name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
      
    - name: Install system dependencies (for tkinter)
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
      
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
    - name: Run tests
      run: |
        cd todo_app && python -m unittest test_app.py